#change to be genereic 
DATA_NAME: 'LaManno'
DIRECTORIES:
  OUTPUT_DIR: '/home/emiliano/projects/def-cdesouza/Lab/MRNA_pipe/Pipe/output/visualize'
  DATA_DIRECTORY: '/home/emiliano/projects/def-cdesouza/Lab/data/raw/LaManno'
  PREPROCESS_DIRECTORY: '/home/emiliano/projects/def-cdesouza/Lab/pre'
  TRUE_CLUSTER_DIR: '/home/emiliano/projects/def-cdesouza/Lab/data/true/LaManno/'
  BACKSPIN_CLUSTER: '/home/emiliano/projects/def-cdesouza/Lab/MRNA_pipe/Pipe/output/cluster/backspin'
  GINICLUST_CLUSTER: '/home/emiliano/projects/def-cdesouza/Lab/MRNA_pipe/Pipe/output/cluster/giniclust'
  SC3_CLUSTER: '/home/emiliano/projects/def-cdesouza/Lab/MRNA_pipe/Pipe/output/cluster/sc3'
  SEURAT_CLUSTER: '/home/emiliano/projects/def-cdesouza/Lab/MRNA_pipe/Pipe/output/cluster/seurat'
SOFTWARE:
  PURITY: '/home/emiliano/projects/def-cdesouza/Lab/MRNA_pipe/Pipe/code/Vizualize/AIR+VM+Purity.R'
  cMATRIX: '/home/emiliano/projects/def-cdesouza/Lab/MRNA_pipe/Pipe/code/Vizualize/cMatrix.R'
  HEATMAP: '/home/emiliano/projects/def-cdesouza/Lab/MRNA_pipe/Pipe/code/Vizualize/heatmap.R'
  TSNE+PCA: '/home/emiliano/projects/def-cdesouza/Lab/MRNA_pipe/Pipe/code/Vizualize/tSNE+PCA.R'
LOG:
  VIZ_LOG: '/home/emiliano/projects/def-cdesouza/Lab/'
