#change to be genereic 
DATA_NAME: 'LaManno'
DIRECTORIES:
  OUTPUT_DIR: '/home/emiliano/projects/def-cdesouza/Lab/Epiclomal/snakemake/synthetic_data_epiclomal'
  DATA_DIRECTORY: '/home/emiliano/projects/def-cdesouza/Lab/data/raw/LaManno'
  PREPROCESS_DIRECTORY: '/home/emiliano/projects/def-cdesouza/Lab'

PARAMS:
  DATA_NAME: 
  
SOFTWARE:
  PREPROCESS_CEF_CONVERT: '/home/emiliano/projects/def-cdesouza/Lab/MRNA_pipe/Pipe/code/preprocess/Cef_convert.R'
  PREPROCESS_DATA: '/home/emiliano/projects/def-cdesouza/Lab/MRNA_pipe/Pipe/code/preprocess/preprocess.R'
  eval_software: '/home/emiliano/projects/def-cdesouza/Lab/Epiclomal/scripts/eval_epiclomal.R'

LOG:
  PREPROCESS_LOG: '/home/emiliano/projects/def-cdesouza/Lab/'
