
DATA_NAME: 'LaManno'
DIRECTORIES:
  OUTPUT_DIR: '../../../MRNA_pipe/output/preprocess'
  DATA_DIRECTORY: '../../../data/raw/LaManno'
  PREPROCESS_DIRECTORY: '../../..'
  CEF_INPUT: '../../../MRNA_pipe/output/preprocess'
  
SOFTWARE:
  PREPROCESS_CEF_CONVERT: '../../../MRNA_pipe/rnaPipeline/preprocess/Cef_convert.R'
  PREPROCESS_DATA: '../../../MRNA_pipe/rnaPipeline/preprocess/preprocess.R'

LOG:
  PREPROCESS_LOG: '../../../'
