#change to be genereic 
DATA_NAME: 'LaManno'
DIRECTORIES:
  OUTPUT_DIR: '../../../MRNA_pipe/output/visualize'
  DATA_DIRECTORY: '../../../data/raw/LaManno'
  PREPROCESS_DIRECTORY: '../../../pre'
  TRUE_CLUSTER_DIR: '../../../data/true/LaManno/'
  BACKSPIN_CLUSTER: '../../../MRNA_pipe/output/cluster/backspin'
  GINICLUST_CLUSTER: '../../../MRNA_pipe/output/cluster/giniclust'
  SC3_CLUSTER: '../../../MRNA_pipe/output/cluster/sc3'
  SEURAT_CLUSTER: '../../../MRNA_pipe/output/cluster/seurat'
SOFTWARE:
  PURITY: '../../../MRNA_pipe/rnaPipeline/Vizualize/AIR+VM+Purity.R'
  cMATRIX: '../../../MRNA_pipe/rnaPipeline/Vizualize/cMatrix.R'
  HEATMAP: '../../../MRNA_pipe/rnaPipeline/Vizualize/heatmap.R'
  TSNE+PCA: '../../../MRNA_pipe/rnaPipeline/Vizualize/tSNE+PCA.R'
LOG:
  VIZ_LOG: '../../../'
